In [104]:
print("Hello World")

Hello World


In [105]:
print('Hello World')
print('Welcome to Python Programming!')
print('Good Bye.')

Hello World
Welcome to Python Programming!
Good Bye.


In [106]:
num = 10

In [107]:
print(num)

10


In [108]:
type(num)

int

In [109]:
num1 = 56.89
name = 'Tushar'

In [110]:
type(num1)

float

In [111]:
type(name)

str

In [112]:
name

'Tushar'

In [113]:
print(type(num))
print(type(num1))
print(type(name))

<class 'int'>
<class 'float'>
<class 'str'>


In [114]:
print("My name is",name,'and marks are',num)

My name is Tushar and marks are 10


In [115]:
print(f"My name is {name} and marks are {num}")

My name is Tushar and marks are 10


In [116]:
num1 = 78    # This is first number
num2 = 22
add = num1 + num2   # Find addition
print("Addition is:", add)  # Print Addition

Addition is: 100


#### Python Operators

In [117]:
num1 = 56
num2 = 14
result = num1 + num2
result

70

In [118]:
num1 - num2

42

In [119]:
num1 * num2

784

In [120]:
num1 / num2

4.0

In [121]:
num1 ** num2   # Power of

2982856619293778479415296

In [122]:
# Relational
num1 > num2

True

In [123]:
num1 < num2

False

In [124]:
num1 >= num2

True

In [125]:
num1 <= num2

False

In [126]:
num1 == num2

False

In [127]:
num1 != num2

True

In [128]:
num

10

In [129]:
num += 2
num

12

In [130]:
num1 > num2 and num1 > 100

False

In [131]:
num1 > num2 and num1 < 100

True

In [132]:
num1 > num2 or num1 > 100

True

In [133]:
not num1 > num2 

False

#### Input function

In [134]:
num1 = int(input('Enter first number: '))
num2 = int(input('Enter second number: '))
add = num1 + num2
print("Addition is:", add)

Enter first number:  78
Enter second number:  78


Addition is: 156


In [139]:
cel = int(input('Enter first number: '))
far = 9/5 * cel + 32
print("Fahrenhite temp:", far)

Enter first number:  00


Fahrenhite temp: 32.0


In [140]:
pass = 90

SyntaxError: invalid syntax (1286397347.py, line 1)

#### Decision Making Statements

In [141]:
num = int(input('Enter the number: '))
if num > 0:
    print("Positive")
elif num == 0:
    print("ZERO")
else:
    print("Negative")

Enter the number:  78


Positive


#### Loops

In [142]:
count = 0 
while count < 10: 
    print('Tushar')
    count += 1

Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar


In [143]:
for x in 5,3,2,4,7,8: 
    print(x)

5
3
2
4
7
8


In [144]:
for x in 5,3,2,4,7,8: 
    print(x*x)

25
9
4
16
49
64


In [145]:
for x in "Tushar": 
    print(x*50)

TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT
uuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuu
ssssssssssssssssssssssssssssssssssssssssssssssssss
hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
rrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr


In [146]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [147]:
for i in range(5):
    print(i * i)

0
1
4
9
16


In [148]:
list(range(4,10))

[4, 5, 6, 7, 8, 9]

In [149]:
list(range(1,10,2))

[1, 3, 5, 7, 9]

In [150]:
for i in range(10):
    print('Tushar')

Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar
Tushar


In [151]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


In [152]:
for i in range(10):
    if i == 5:
        continue
    print(i)

0
1
2
3
4
6
7
8
9


In [153]:
for i in range(10):
    if i % 2 == 1:
        continue
    print(i)

0
2
4
6
8


#### Data Structures

In [154]:
a = [1,2,3,4,5,6]
b = (1,2,3,4,5,6)
c = {1,2,3,4,5,6}
d = {1:2,3:4,5:6}

In [155]:
a[3]

4

In [156]:
a[3] = 78
a

[1, 2, 3, 78, 5, 6]

In [157]:
b[4] = 78

TypeError: 'tuple' object does not support item assignment

In [ ]:
c = {4,5,4,3,4,4,5,6,7,9}

In [158]:
c

{1, 2, 3, 4, 5, 6}

In [159]:
d

{1: 2, 3: 4, 5: 6}

In [160]:
d[3]

4

#### Functions

In [161]:
# Function Definition
def show(): 
    print("Welcome!")
    print("Hello World")

In [162]:
# Function call
show()

Welcome!
Hello World


In [163]:
def square(n):
    sq = n * n
    return sq

In [164]:
square(5)

25

In [165]:
5 * square(5)

125

In [166]:
print("Square is", square(5))

Square is 25


In [167]:
def add(x=7, y=2, z=3):
    addition = x + y + z
    return addition

In [168]:
add(5,4,1)

10

In [169]:
add(5,4)

12

In [170]:
add(5)

10

In [171]:
add()

12

In [172]:
add(z=2)

11

In [173]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [174]:
print(num1, num2)

78 78


In [175]:
print(num1, num2, sep='_')

78_78


In [176]:
print(num1, end = ' ') 
print(num2)

78 78


#### Modules

In [177]:
import math

In [178]:
math.sqrt(45)

6.708203932499369

In [179]:
math.log(34)

3.5263605246161616

In [180]:
math.pi

3.141592653589793

In [181]:
math.e

2.718281828459045

In [182]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

In [183]:
import math  as m

In [184]:
m.sqrt(9)

3.0

In [186]:
m.pi

3.141592653589793

In [187]:
from math import log, pi, factorial

In [188]:
pi

3.141592653589793

In [189]:
log(100)

4.605170185988092

In [190]:
factorial(5)

120

#### Class and Object

In [194]:
class Person:                        # Class definition
    def __init__(self, n, a):        # Constructor function 
        self.name = n                # name & age -> class variables
        self.age = a 
    def show(self):                  # Function of class
        print('Values are:', self.name, self.age)
    def isEligible(self):
        if self.age >= 18:
            return True
        else:
            return False

In [195]:
# Create the object
p1 = Person("Ajay", 23)

In [198]:
print(p1.name)

Ajay


In [199]:
p1.age

23

In [200]:
p1.show()

Values are: Ajay 23


In [201]:
p2 = Person("Priya", 16)

In [202]:
p2.show()

Values are: Priya 16


In [203]:
p1.isEligible()

True

In [204]:
p2.isEligible()

False

In [206]:
p3 = Person("Ram", 34)
p3.name = "Raj"
p3.show()
p3.isEligible()

Values are: Raj 34


True

In [207]:
name = 'Tushar'

In [208]:
name.upper()

'TUSHAR'

In [209]:
num = [56,11,24,3,6,5,8]

In [210]:
num.append(12)
num

[56, 11, 24, 3, 6, 5, 8, 12]

In [211]:
num.sort()
num

[3, 5, 6, 8, 11, 12, 24, 56]

In [212]:
num.sort(reverse=True)

In [213]:
num

[56, 24, 12, 11, 8, 6, 5, 3]

#### Array Operations

In [216]:
# Array is collection of same type of data 

In [217]:
import numpy as np

In [218]:
a1 = np.array([56,43,23,16,54,18])

In [219]:
a1

array([56, 43, 23, 16, 54, 18])

In [220]:
a1[4]

54

In [221]:
a1[4] = 67
a1

array([56, 43, 23, 16, 67, 18])

In [222]:
a1.dtype

dtype('int64')

In [223]:
a1 = np.array([56,43,23,16,54,18], dtype = np.int16)

In [224]:
a1

array([56, 43, 23, 16, 54, 18], dtype=int16)

In [225]:
a1.dtype

dtype('int16')

In [229]:
a2 = np.array([56.34, 78.89, 12.34, 96.34, 53])

In [230]:
a2

array([56.34, 78.89, 12.34, 96.34, 53.  ])

In [231]:
a2.dtype

dtype('float64')

In [232]:
a2[4]

53.0

In [233]:
a2.max()

96.34

In [234]:
a2.mean()

59.382000000000005

In [235]:
a2.sum()

296.91

In [236]:
a3 = np.array([[5,6,7],[4,5,6],[7,1,2],[4,0,9]])

In [237]:
a3

array([[5, 6, 7],
       [4, 5, 6],
       [7, 1, 2],
       [4, 0, 9]])

In [239]:
a3[2,2]

2

In [240]:
a3[2][2]

2

In [241]:
a3.shape

(4, 3)

In [242]:
a3.size

12

In [243]:
a1

array([56, 43, 23, 16, 54, 18], dtype=int16)

In [244]:
a1 + 10

array([66, 53, 33, 26, 64, 28], dtype=int16)

In [245]:
a1 / 2

array([28. , 21.5, 11.5,  8. , 27. ,  9. ])

In [246]:
a1 + a1

array([112,  86,  46,  32, 108,  36], dtype=int16)

In [247]:
a1 > 25

array([ True,  True, False, False,  True, False])

In [248]:
a1[a1 > 25]

array([56, 43, 54], dtype=int16)

In [249]:
a1 = a1 + 10

In [250]:
a1

array([66, 53, 33, 26, 64, 28], dtype=int16)